version: '3.8'
services:
  db:
    image: 'postgres:15-alpine'
    container_name: db_postgres
    environment:
      POSTGRES_USER: adm
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: tool_db
    ports:
     - "5432:5432"
    restart: unless-stopped

  eureka:
    build: ./registry-service-eureka
    container_name: eureka-service
    ports:
      - "8761:8761"

  tool-app:
    build: ./tool-service
    container_name: tool-api
    depends_on:
      - db
    ports:
     - "8080:8080"
    restart: unless-stopped