spring:
  sql:
    init:
      mode: always
  application:
    name: tool-app
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: false
  datasource:
    url: jdbc:postgresql://localhost:5432/tool_db
    driver-class-name: org.postgresql.Driver
    username: adm
    password: 123

app:
  security:
    jwt:
      key: 413F4428472B4B6250655368566D5970337336763979244226452948404D6351
      expiration: 36000000